name: Build LocalSRT

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Linux binary
        run: |
          pyinstaller localsrt_v3.1.py --onefile \
            --add-data "bin/linux:bin" \
            --name localSRT-linux
      - name: Upload localSRT Linux to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/localSRT-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Windows exe
        run: |
          pyinstaller localsrt_v3.1.py --onefile `
            --add-data "bin/windows;bin" `
            --name localSRT-windows

      - name: Upload localSRT Windows to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/localSRT-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build macOS app
        run: |
          pyinstaller localsrt_v3.1.py --onefile \
            --add-data "bin/macos:bin" \
            --name localSRT-macos

      - name: Upload localSRT macOS to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/localSRT-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}
    
